---

mongodb_replication_replset: rp0                  # Enable replication <setname>[/<optionalseedhostlist>]
mongodb_replication_replindexprefetch: "all"      # specify index prefetching behavior (if secondary) [none|_id_only|all]
mongodb_replication_oplogsize: 1024               # specifies a maximum size in megabytes for the replication operation log
mongodb_package: mongodb
mongodb_version: "1:3.6.3-0ubuntu1.1"

mongodb_user_admin_name: siteUserAdmin
mongodb_user_admin_password: "{{ lookup('env','ANSIBLE_MONGO_SITEUSERADMIN_PASSWORD') }}"

mongodb_login_host: "{{ hostvars[groups['mongo_master'][0]].ansible_default_ipv4.address }}"

mongodb_users:
  - {
    name: testUser,
    password: "{{ lookup('env','ANSIBLE_MONGO_TESTUSER_PASSWORD') }}",
    roles: readWrite,
    database: admin
  }


ufw_rules:
  - { port: 22, rule: allow, from_ip: '0.0.0.0', comment: 'Allow ssh' }
  - { port: 27017, rule: allow, from_ip: "87.225.41.109", comment: 'Allow to mongo from me' }
  - { port: 27017, rule: allow, from_ip: "{{ hostvars[groups['mongo'][0]].ansible_eth0.ipv4.address }}", comment: 'Allow to mongo from mongo1' }
  - { port: 27017, rule: allow, from_ip: "{{ hostvars[groups['mongo'][1]].ansible_eth0.ipv4.address }}", comment: 'Allow to mongo from mongo2' }
  - { port: 27017, rule: allow, from_ip: "{{ hostvars[groups['mongo'][2]].ansible_eth0.ipv4.address }}", comment: 'Allow to mongo from mongo3' }

ufw_default_input_policy: deny
ufw_default_output_policy: allow
ufw_default_forward_policy: deny
