---

- hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: Bootsrap Python2 for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when: output.stdout != ""
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Add python tools
      apt:
        name:
          - python-pip 
          - python-setuptools
- hosts: mongo
  become: true
  gather_facts: yes
  roles:
    - ufw

- hosts: mongo
  become: true
  gather_facts: yes
  roles:
    - role: mongodb

